name: a_bible
description: Leitor de Bíblia com funcionalidades avançadas - leitura, bookmarks, temas personalizados e muito mais
publish_to: 'none'

version: 2.0.4+7

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  scrollable_positioned_list: ^0.3.8
  
  # Database
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0
  path: ^1.8.3
  archive: ^4.0.7
  
  # UI & Charts
  fl_chart: ^1.1.0
  google_fonts: ^6.1.0
  
  # State Management
  provider: ^6.0.5
  
  # Utilities
  intl: ^0.20.2
  uuid: ^4.1.0
  shared_preferences: ^2.2.2
  flutter_tts: ^4.2.3
  
  # Ads
  google_mobile_ads: ^6.0.0
  in_app_purchase: ^3.1.13
  
  # Icons
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.2
  flutter_native_splash: ^2.4.4
  package_info_plus: ^9.0.0
  wakelock_plus: ^1.1.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/biblias.zip
    - assets/icon.png

# Configuração do ícone do app
flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon.png"

# Splash screen configuration
flutter_native_splash:
  color: "#ffffff"
  image: assets/icon.png
  android: true
  ios: false
  web: false
